[package]
name = "libntgcalls-sys"
version = "0.1.0"
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]

[features]
default = ["bundled"]
bundled = []
