name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: "native"
            cibw_os_build: "manylinux_"
          # - os: arm64-server
          #   cibw_archs: "aarch64"
          #   cibw_os_build: "manylinux_"
          - os: windows-latest
            cibw_archs: "native"
          - os: macos-14
            cibw_archs: "arm64"
            cibw_os_build: "macosx_arm64"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Linux dependencies
        run: sudo apt update
        if: contains(matrix.os, 'ubuntu')

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Build
        run: cargo build --verbose --all-features

      - name: Test
        run: cargo test --verbose --all-features

      - name: Clippy
        run: cargo clippy --verbose  --all-features -- -D warnings
        
      - name: Audit
        run: cargo audit --deny warnings